sudo: required
# The default environment is Ubuntu 12.04, which only has GCC 4.6.
dist: trusty
language: cpp
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3
script:
  - make
  - make check
compiler:
  - gcc
  - clang
